### ISSUE TITLE
A little bit confuse with KeyError: 'a'

### ISSUE THREAD

**Issue by JSharp4273** [NVlabs/MUNIT#47]
Hello

I am trained MUNIT to make conversion of from 14 bit per pixel infrared data to colour images.
The training run without any particular issue.
Then I try to evaluate my model by tuning the test.py scripty but I encounter that message:

Traceback (most recent call last):
  File "test.py", line 55, in <module>
    trainer.gen_a.load_state_dict(state_dict['a'])
KeyError: 'a'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 58, in <module>
    state_dict = pytorch03_to_pytorch04(torch.load(opts.checkpoint), opts.trainer)
  File "/hdd1/prog/MUNIT/utils.py", line 372, in pytorch03_to_pytorch04
    state_dict['a'] = __conversion_core(state_dict_base['a'], trainer_name)
KeyError: 'a'

If I well understand it does not find the weights ?
After the training I used the file "optimizer.pt" as model because I did not have a more explicit filename regarding the name of my dataset.

**Comment by xiang-zhe** [comment]
hi, i got the problem too, did u fix  it? @JSharp4273 

Traceback (most recent call last):
  File "test.py", line 55, in <module>
    trainer.gen_a.load_state_dict(state_dict['a'])
KeyError: 'a'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 58, in <module>
    state_dict = pytorch03_to_pytorch04(torch.load(opts.checkpoint), opts.trainer)
  File "/home/xiang/git/MUNIT/utils.py", line 384, in pytorch03_to_pytorch04
    state_dict['a'] = __conversion_core(state_dict_base['a'], trainer_name)
KeyError: 'a'

**Comment by xiang-zhe** [comment]
if use gen_0****.pt, it's ok, but what's the dis_0****.pt and optimizer.pt, 
"gen_a , auto-encoder for domain a"  in trainer.py line17 that i could understand,  but "dis_a, discriminator for domain a "   in trainer.py line19 that i don't think i understand,   and more  the model optimizer.pt just use to help training? and what do model dis_0***.pt for ?
just use the model  gen_0***.pt when test ?
anyone can help me? thank you very much

**Comment by WanyiLi** [comment]
I meet the same problem too. I use the gen_*.pt when test.
