### ISSUE TITLE
Is this full code ?

### ISSUE THREAD

**Issue by taki0112** [NVlabs/MUNIT#5]
Hi

1. If you look at configs, there is no information about animal translation.
When will you upload it? 
Is it ok to just run as hyper-parameter like edge2shoes?

2. The paper used a common gan loss
You used lsgan in your code. What was the difference in the results when comparing the two?

**Comment by mingyuliutw** [comment]
For 2, we use LSGAN as specified in Section 5.1 in the paper.
For 3, we use all the training images in the datasets for training.

**Comment by zhf459** [comment]
I failed to run the command `"python test.py --config configs/edges2shoes.yaml --input inputs/edge.jpg --output_folder outputs --checkpoint models/edges2shoes.pt --a2b 1"` and got an error:
```
Traceback (most recent call last):
  File "/home/zeng/work/pycharm/MUNIT/test.py", line 76, in <module>
    main(sys.argv)
  File "/home/zeng/work/pycharm/MUNIT/test.py", line 44, in main
    trainer.gen_a.load_state_dict(state_dict['a'])
  File "/home/zeng/.conda/envs/conda-python3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 538, in load_state_dict
    .format(name))
KeyError: 'unexpected key "enc_content.model.0.norm.running_mean" in state_dict'
```
anything wrong? thanks.

**Comment by XiangyuWu** [comment]
@zhf459 I think you'd better check the version of the dependencies.
