### ISSUE TITLE
Error while trying python train.py --config configs/doc2doc.yaml (Custom Dataset)

### ISSUE THREAD

**Issue by akshaydp1995** [NVlabs/MUNIT#68]
Traceback (most recent call last):
  File "train.py", line 45, in <module>
    train_display_images_b = torch.stack([train_loader_b.dataset[i] for i in range(display_size)]).cuda()
  File "train.py", line 45, in <listcomp>
    train_display_images_b = torch.stack([train_loader_b.dataset[i] for i in range(display_size)]).cuda()
  File "/content/MUNIT/data.py", line 119, in __getitem__
    path = self.imgs[index]
IndexError: list index out of range

**Comment by APhun** [comment]
Hi,
have you solved the question? I had the same problem

**Comment by APhun** [comment]
Hi,
have you solved the problem? I had the same problem

**Comment by stillstream** [comment]
Hi,
have you solved the problem? I had the same problem @APhun @akshaydp1995

**Comment by BassantSamy** [comment]
reducing the display_size from 8 to 3 did the trick for me
